version: "3"

services:
  SniperCallsbot:
    image: drakkarsoftware/SniperCallsbot:stable
    volumes:
       - ./logs:/SniperCallsbot/logs
       - ./backtesting:/SniperCallsbot/backtesting
       - ./tentacles:/SniperCallsbot/tentacles
       - ./user:/SniperCallsbot/user
    ports:
       - ${PORT:-80}:${PORT:-5001}
    restart: always
  
  watchtower:
    image: containrrr/watchtower
    restart: always
    command: --cleanup --include-restarting
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
